### ISSUE TITLE
Get User Input for Reading Frame

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#104]
Currently, the user has to go into the `CoreExecutor.java` file, scroll down to line 140, and then change the value of the reading frame. This should be changed to get input from the user at the start of the program.

**Comment by frankschmitt** [comment]
I'd like to give this one a try. One question: do you want to get the input interactively (via a dialog) or as a command-line argument or both?

**Comment by Verisimilitude11** [comment]
We're planning on creating a GUI soon, but for now just asking the user for input through the Scanner class should be good. Would you be interested in helping us with a GUI when we get to that?

**Comment by Verisimilitude11** [comment]
Actually, this issue has already been resolved. Could you please implement a GUI version to allow the user to select from options? Thanks!

**Comment by Verisimilitude11** [comment]
Thanks @frankschmitt for working on this issue! To support the mission of DNAnalyzer, I'd really appreciate it if you would give this repository a star! Thanks again for your contributions!

**Comment by Verisimilitude11** [comment]
@frankschmitt any updates?

**Comment by frankschmitt** [comment]
> @frankschmitt any updates?

I thought this had already been resolved? You wrote:

> Actually, this issue has already been resolved. Could you please implement a GUI version to allow the user to select from options?

Regarding the GUI version:  I've asked user RamAlbot in https://github.com/Verisimilitude11/DNAnalyzer/issues/121 whether they're already working on this (to avoid duplicate work). But since I didn't get any response so far (it's been three days), I'll take a look.

**Comment by Verisimilitude11** [comment]
I apologize, I forgot that this feature was already implemented in the CLI. Sounds good, I assigned the issue to you. Thanks for working on this!
