### ISSUE TITLE
Get User Input for MIN and MAX in Reading Frames

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#107]
Currently, the user has to go into the `CoreExecutor.java` file, scroll down to line 141 & 142, and then change the value of the reading frame. This should be changed to get input from the user at the start of the program.

**Comment by Lumary2** [comment]
Good morning, I would like to work on this.

**Comment by Verisimilitude11** [comment]
Thanks @Lumary2 for working on this issue! To support the mission of DNAnalyzer, I'd really appreciate it if you would give this repository a star! Thanks again for your contributions!
