### ISSUE TITLE
Take Input From 2+ DNA Files and Compare Them For Similarities

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#108]
The DNA sequence may be [aligned](https://en.wikipedia.org/wiki/Sequence_alignment) with other DNA sequences to identify [homologous sequences](https://en.wikipedia.org/wiki/Sequence_homology) and locate the specific [mutations](https://en.wikipedia.org/wiki/Mutation) that make them distinct. These techniques, especially [multiple sequence alignment](https://en.wikipedia.org/wiki/Multiple_sequence_alignment), are used in studying [phylogenetic](https://en.wikipedia.org/wiki/Phylogenetics) relationships and protein function. For example, this could be used to compare a Neanderthal gene to the same gene in Homo Sapiens.

**Comment by achiverram28** [comment]
Could you give more insights as it how would I be able to contribute

**Comment by Verisimilitude11** [comment]
Hi @achiverram28, ideally you would create a class that compares 2 DNA strings inputted and tells the user which parts are common and which are distinct. Let me know if you have any further questions.

**Comment by achiverram28** [comment]
Ok . sure I would like to work on this , please tell me if you have any standard file which I can follow for my work.
Please assign me this

**Comment by Verisimilitude11** [comment]
Alright. Use `assets/dna/random/dnalong.fa` and serine (or ser) for testing. 10-10000 codons and the 1st reading frame should be fine for testing purposes.

**Comment by Verisimilitude11** [comment]
Let me know if you have any further questions.

**Comment by achiverram28** [comment]
Please give a much more detailed documentation , to give more clear insights , also please provide the model java file which I can follow to code

**Comment by achiverram28** [comment]
![DFCA949F-398A-482C-99A7-1FEA5EF9005F_4_5005_c](https://user-images.githubusercontent.com/97288756/194301931-9bd6e344-6181-4871-b886-d8a28900ab8c.jpeg)

**Comment by achiverram28** [comment]
I know Java , I am asking for detailing because I am a beginner to open - source , so as it keep things very organised . Hoping you wont mind

**Comment by Verisimilitude11** [comment]
@achiverram28 any updates?

**Comment by LimesKey** [comment]
I believe this is what #228 is trying to solve, can I close this? The DIAMOND sequence aligner tool is likely a lot better and more efficient than 1 person could code.

**Comment by Verisimilitude11** [comment]
Good point, let's close this then. I'm going to ask a couple people today on how the DIAMOND sequence aligner tool could be implemented.
