### ISSUE TITLE
Switch build to Gradle build tool

### ISSUE THREAD

**Issue by frankschmitt** [Verisimilitude11/DNAnalyzer#117]
**Is your feature request related to a problem? Please describe.**
Currently, building / running the project can only be done by executing ```javac Main.java``` / ```java Main``` manually (or running Main from your IDE, e.g. Eclipse). This is especially confusing for new users, who are used to Maven or Gradle and simply wish to run 

```
gradle build
```

to build their project without having to worry about the dependencies etc.

Also, gradle allows publishing the package to Maven Central, running the tests etc. in a very straight-forward way.

**Describe the solution you'd like**
I'd like a project setup that allows the user to simply execute

```
gradle build
```

to build the project and 

```
gradle run
```

to run it.

**Describe alternatives you've considered**
An alternative to Gradle would be [Maven|https://maven.apache.org/]. Similar features, mostly a matter of preferences (personally, I prefer Gradle).

**Additional context**
If this sounds sensible to you, I'd be willing to implement it :-)

**Comment by Verisimilitude11** [comment]
Sure, sounds great! I would prefer using Gradle as well. One question, would a user still be able to run the program using `main`?

**Comment by Verisimilitude11** [comment]
Feel free to get started on this!

**Comment by naXa777** [comment]
>  would a user still be able to run the program using main?

Yes, sure.

**Comment by Verisimilitude11** [comment]
> > would a user still be able to run the program using main?
> 
> Yes, sure.

Sounds good, I'll approve your PRs as they come. Afterwards, perhaps we can set up a GitHub Actions pipeline for Gradle.

**Comment by Verisimilitude11** [comment]
Once you implement this, it would be great if you could create a separate PR with documentation.
