### ISSUE TITLE
Documentation for CLI in README

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#130]
By @Nv7-GitHub:
This uses CLI arguments instead of `stdin`.  For example, you can do 
```sh
<executable> assets/dna/random/dnalong.fa --amino=ser
```
or
```sh
<executable> assets/dna/random/dnalong.fa --amino=ser --min=0 --max=100
```

Help message:
```
Usage: DNAnalyzer [-hV] --amino=<aminoAcid> [--max=<maxCount>]
                  [--min=<minCount>] DNA
A program to analyze DNA sequences.
      DNA                   The FASTA file to be analyzed.
      --amino=<aminoAcid>   The amino acid representing the start of a gene.
  -h, --help                Show this help message and exit.
      --max=<maxCount>      The maximum count of the reading frame.
      --min=<minCount>      The minimum count of the reading frame.
  -V, --version             Print version information and exit.
```

**Comment by aminisonya** [comment]
I'd like to work on this as part of hacktoberfest, but I'm confused on what you want added here. Do you want this information added to the top level readme file?

**Comment by Verisimilitude11** [comment]
Yes please! Just replace what is currently under the `Usage` header with this content. It would be really helpful if you would expand on this and make it easier to understand for new users. Thanks for your help and interest in contributing to DNAnalyzer!

**Comment by aminisonya** [comment]
I don't see a `Usage` header in the readme. Do you want me to add one?

**Comment by Verisimilitude11** [comment]
Sure, I think that I haven't merged that PR yet. Feel free to add a `Usage` header.
