### ISSUE TITLE
Move the CoreExecutor stuff into the run method

### ISSUE THREAD

**Issue by Speedro** [Verisimilitude11/DNAnalyzer#154]
https://github.com/Verisimilitude11/DNAnalyzer/pull/126#issuecomment-1265835386

The CoreExecutor class should only be responsible for one thing - running the app. Try to refactor it so that all the logic related to actually running the app stays at one place.

**Comment by Nv7-GitHub** [comment]
I'm going to make a PR that does this

**Comment by Nv7-GitHub** [comment]
Did this with #155
