### ISSUE TITLE
Protein finding

### ISSUE THREAD

**Issue by Nv7-GitHub** [Verisimilitude11/DNAnalyzer#156]
Being able to find a protein/test if it exists in the dna sequence is useful in DNA analyzing. I will implement it as an optional parameter to the CLI.

**Comment by Verisimilitude11** [comment]
I got the whole human body's DNA from The Human Genome Project. I'll send you the file via Discord later today. The thing is, we need to implement an efficient algorithm for string searching - we can potentially look into the Needleman-Wunsch algorithm. This feature would pave the way for ML analysis in the future.

**Comment by Nv7-GitHub** [comment]
Actually it seems like the Needleman-Wunsch isn't for exact string matching, instead it can rate segments on DNA based on how close of a match they are (perhaps? the wikipedia page was kind of confusing)

**Comment by Verisimilitude11** [comment]
Huh, weird. It'll still be somewhat useful later on actually.

**Comment by Nv7-GitHub** [comment]
Yeah, although its pretty complicated and would require some more research and testing probably

**Comment by Verisimilitude11** [comment]
@Nv7-GitHub you already implemented this feature right?

**Comment by Nv7-GitHub** [comment]
Yeah, I implemented a simple search, although not the Needleman-Wusch algorithm

**Comment by Verisimilitude11** [comment]
Okay cool, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
