### ISSUE TITLE
Video In README Not Working

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#157]
Host on Azure and use <iframe> to embed.

**Comment by zackrhodes86** [comment]
Can I be assigned this issue? I'd love to help out

**Comment by Verisimilitude11** [comment]
Sure! I assigned it you.

**Comment by Verisimilitude11** [comment]
Please start by starring this repository to show your support. Then, fork it, and open a PR with the changed you make. I think that for this issues, the video would need to be hosted elsewhere or enter it directly using markdown instead of pure HTML. Let me know if you have any questions!

**Comment by Verisimilitude11** [comment]
Thanks for working on this, @zackrhodes86! I would really appreciate it if you would star this repository if you haven't done so yet!
