### ISSUE TITLE
Add All Docs to Repo Wiki

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#160]
![image](https://user-images.githubusercontent.com/96280466/194189049-fd02d65e-d430-4cef-941f-36b9153fc9f9.png)

**Comment by Verisimilitude11** [comment]
![image](https://user-images.githubusercontent.com/96280466/194188984-442d0d74-8d59-4577-8bba-5e91b94c4238.png)

**Comment by krishnabiradar310802** [comment]
@Verisimilitude11 Which docs do you want me to add to Wiki?

**Comment by plopez26DPU** [comment]
Can you assign me this issue please

**Comment by plopez26DPU** [comment]
@Verisimilitude11 

Is this what you were wanting? Or did you want the docs to be scrollable through the whole wiki? 

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/90722929/196310114-5fd60096-0f3b-4abc-8b3d-6c13db14f066.png">

**Comment by plopez26DPU** [comment]
Check the changes I made from the above screenshot, https://github.com/plopez26DPU/DNAnalyzer/wiki#documents

Let me know which style you would want for final product

**Comment by Verisimilitude11** [comment]
The current style looks great! Could you please put it into the main repository? /Verisimilitude11/DNAnalyzer? Thanks so much for working on this!

**Comment by plopez26DPU** [comment]
Yep! I will finish it tomorrow,  no problem 😊

**Comment by Verisimilitude11** [comment]
All good, thanks again!

**Comment by plopez26DPU** [comment]
I am not able to do a pull request for this, but I have updated the main wiki

https://github.com/Verisimilitude11/DNAnalyzer/wiki

**Comment by Verisimilitude11** [comment]
Looks great! Thanks for working on this.

**Comment by plopez26DPU** [comment]
No problem! Make sure to close the issue :)
