### ISSUE TITLE
Add Gradle Usage Instructions to README

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#165]
Add gradle instruction (from @Nv7-GitHub ):

Now, run the following to build it
```
./gradlew build
```
Then, use this to run the CLI
```
java -jar build/libs/DNAnalyzer.jar <arguments>
```
Also, picocli is now an external dependency so the massive source isn't part of the repo

**Comment by Saket2** [comment]
Opened a PR for this - https://github.com/Verisimilitude11/DNAnalyzer/pull/175
