### ISSUE TITLE
(JAVA-W1035) Classes that contain only static members should not be instantiated

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#170]
## Description
This code seems to be creating an instance of a class with only static members. Such a class does not need to be instantiated, since all members can be accessed with just the class itself.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1035/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1035/occurrences/)

**Comment by AbbasSalloum** [comment]
Hello, could i work on this?

**Comment by Verisimilitude11** [comment]
Sure, feel free to let me know if you have any questions.

**Comment by AbbasSalloum** [comment]
Hey just wondering is there a class called Main ? since i could not find it

**Comment by Verisimilitude11** [comment]
https://github.com/Verisimilitude11/DNAnalyzer/blob/main/src/main/java/DNAnalyzer/Main.java?
