### ISSUE TITLE
Adding contributers profile into README.md

### ISSUE THREAD

**Issue by sb-decoder** [Verisimilitude11/DNAnalyzer#173]
**Is your feature request related to a problem? Please describe.**
I want to  add contributers profiles into README.md.

**Comment by Verisimilitude11** [comment]
Could you please elaborate further on this?

**Comment by Verisimilitude11** [comment]
Sure, feel free to open a pull request for this.

**Comment by Verisimilitude11** [comment]
Thanks for working on this, @sb-decoder! I would really appreciate it if you would star this repository if you haven't done so yet!

**Comment by Verisimilitude11** [comment]
@sb-decoder would you like to join our Discord server: https://discord.gg/5ShCNmyp

**Comment by Verisimilitude11** [comment]
@sb-decoder would you like to join our Discord server: https://discord.gg/5ShCNmyp
