### ISSUE TITLE
Refactor CodonFrame.equals(Object)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#181]
I've selected [**CodonFrame.equals(Object)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/CodonFrame.java#L61-L70) for refactoring, which is a unit of **9** lines of code and **5** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by sourabhkashyap95** [comment]
@Verisimilitude11 Can you please assign this to my name.

**Comment by Verisimilitude11** [comment]
Yes.

**Comment by sourabhkashyap95** [comment]
Can you please review this PR.
https://github.com/Verisimilitude11/DNAnalyzer/pull/213

**Comment by Verisimilitude11** [comment]
Will look at it tomorrow morning. Thanks for submitting it! Make sure that you star the repository to show your support for our mission here at DNAnalyzer.

**Comment by Verisimilitude11** [comment]
@sourabhkashyap95 your PR fixed this issue, correct?

**Comment by sourabhkashyap95** [comment]
@Verisimilitude11 yes.

**Comment by Verisimilitude11** [comment]
Great. By the way would you be interested in joining our Discord server? The link is here: https://github.com/Verisimilitude11/DNAnalyzer/discussions/256

**Comment by sourabhkashyap95** [comment]
Sure @Verisimilitude11

**Comment by Verisimilitude11** [comment]
@sourabhkashyap95 how far are you on this? Just checking in. 😄

**Comment by sourabhkashyap95** [comment]
@Verisimilitude11 I think this issue has been handled in this PR https://github.com/Verisimilitude11/DNAnalyzer/pull/213/files , does this method still needs more refactoring? if not then you can close this issue.
