### ISSUE TITLE
Refactor Properties.printProteinList(List<String>,String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#188]
I've selected [**Properties.printProteinList(List<String>,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/Properties.java#L37-L72) for refactoring, which is a unit of **32** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Speedro** [comment]
Hey @Verisimilitude11 Is this still an issue?

**Comment by Verisimilitude11** [comment]
Yep, it is! Should I assign it to you?

**Comment by Speedro** [comment]
I mean there is the same issue #76, isn't it?

**Comment by Verisimilitude11** [comment]
Hmm...good point. I'll still leave it here and we'll close it once you submit the pull request for #76. Thanks for noticing this!
