### ISSUE TITLE
Refactor CmdArgs.run()

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#189]
I've selected [**CmdArgs.run()**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/CmdArgs.java#L79-L143) for refactoring, which is a unit of **46** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by singloon** [comment]
@Verisimilitude11 please can you assign the task to me and review the PR

**Comment by Verisimilitude11** [comment]
Assigned.
