### ISSUE TITLE
Add information about DNA and link to README

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#205]
https://www.ancestry.com/c/dna-learning-hub/dna-strands

**Comment by sayan3270** [comment]
i want to work on this issue. i just need to add article on readme ?

**Comment by Verisimilitude11** [comment]
No, you need to paraphrase the content from the article attached into a new .md file under the docs folder. Then, link that .md file to the README for those who are interested in learning more about the science of DNA analyzing. Let me know if you have any other questions!

**Comment by plopez26DPU** [comment]
Any update on this? Willing to take over if needed

**Comment by Verisimilitude11** [comment]
@sayan3270 are you still working on this?

**Comment by HridoyHazard** [comment]
i would like to work on this issue

**Comment by Verisimilitude11** [comment]
@HridoyHazard it seems like someone else is working on this issue already. Could you please work on another issue? Thanks for your interest in contributing to the world of open source!

**Comment by Verisimilitude11** [comment]
@HridoyHazard and @sayan3270 I would really appreciate it if you would star this repository if you haven't done so yet!

**Comment by HridoyHazard** [comment]
ok that's fine assign this to me. i can do it

**Comment by Verisimilitude11** [comment]
No problem @sayan3270. I understand. I would really appreciate it if you would contribute to DNAnalyzer sometime in the future! Thanks again for your interest in the contributing to the world of open source projects.

**Comment by Verisimilitude11** [comment]
> ok that's fine assign this to me. i can do it

@HridoyHazard I assigned the issue to you.

**Comment by Verisimilitude11** [comment]
@HridoyHazard and @sayan3270 please join our Discord server: https://discord.gg/5ShCNmyp

**Comment by Verisimilitude11** [comment]
@HridoyHazard how far are you with this issue?

**Comment by LimesKey** [comment]
I assumed you guys were busy or didn't have time, so I created #282, I hope that was ok. Feel free to edit it since it's only a draft.

**Comment by LimesKey** [comment]
#282
