### ISSUE TITLE
Add Additional Tests Via JUnit

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#206]

**Comment by plopez26DPU** [comment]
Any specific tests you want completed at this time ?

**Comment by plopez26DPU** [comment]
From the source code,  I assume you want only main tested ?

**Comment by Verisimilitude11** [comment]
All of the files under the main folder, yes.

**Comment by plopez26DPU** [comment]
Ok, I will give it a shot

**Comment by Verisimilitude11** [comment]
@plopez26DPU do you need any help with implementing this?

**Comment by plopez26DPU** [comment]
I was attempting this and I think I need more experience with it,  if you have someone else that can do it and I can see what they do, that would be awesome . 👌

**Comment by Verisimilitude11** [comment]
Alright, no worries. I’ll assign it to someone else. Feel free to continue working on some of the other issues that are open (e.g., some documentation stuff, etc.). Thanks again for being a long-time contributor to DNAnalyzer

**Comment by Verisimilitude11** [comment]
We're currently missing tests for the following files:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/96280466/198506650-c18b8c5d-6df3-4736-802c-0dd3b9306b1e.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/96280466/198506665-70ddedb3-b1b5-427b-835c-bb2ef634b79d.png">

**Comment by Verisimilitude11** [comment]
Sure @Ravina-Deogadkar! I assigned it to you.

**Comment by Ravina-Deogadkar** [comment]
Add PR #340
