### ISSUE TITLE
Update Docs to Reflect Current CLI Usage

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#218]
Change screenshots and instructions to use CLI args in the following markdown file: https://github.com/Verisimilitude11/DNAnalyzer/blob/936181dd714855276ea34f55b94e5b53afc8ef0e/docs/samples/serine-dnalong.md

**Comment by plopez26DPU** [comment]
Assign me this :)

**Comment by plopez26DPU** [comment]
Hey @Verisimilitude11 , can you show an example of how to use the CLI find please. I can't seem to get it to work for me
