### ISSUE TITLE
Refactor Properties.formatNucleotideCount(String,int,String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#222]
I've selected [**Properties.formatNucleotideCount(String,int,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/06a0900fa4c196549fea4dc6c5f226efe9741f17/src/main/java/DNAnalyzer/Properties.java#L84-L88) for refactoring, which is a unit of **4** lines of code and **3** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by zaino97** [comment]
Hi @Verisimilitude11,

Can you assign this to me?

Thanks.

**Comment by Verisimilitude11** [comment]
@zaino97 how far are you on this issue?

**Comment by zaino97** [comment]
@Verisimilitude11 i have resolved it in the PR https://github.com/Verisimilitude11/DNAnalyzer/pull/253

**Comment by Verisimilitude11** [comment]
Alright, thanks for working on this!
