### ISSUE TITLE
DIAMOND Implementation, a BLAST fork.

### ISSUE THREAD

**Issue by LimesKey** [Verisimilitude11/DNAnalyzer#228]
[DIAMOND ](https://github.com/bbuchfink/diamond)is an alignment tool for protein and translated DNA searches with high-performance analysis of extensive sequence data. It has some cool features which make it good for running on slow computers and can do a variety of alignments. It says it has various output formats such as tabular, XML and taxonomic classification.

I haven't taken too deep of a look into DIAMOND but I think it may work and be pretty beneficial, it's a fork of [BLAST ](https://en.wikipedia.org/wiki/BLAST_(biotechnology))which was created in 1990. DIAMOND was last updated a few months ago and has semi-active maintainers.

This issue would incorporate a subset of the features found in DIAMOND.

**Comment by LimesKey** [comment]
So what I'm proposing for this project is creating a database with common DNA Gene strings known to cause medical illnesses and conditions, sprinkle some machine learning combined with randomness percentage to account for genetic drift and evolution over time.

To increase accuracy with the reference database DNA is to have lots of metadata with that gene string, such as the average age of the person with that mutated gene string and with correlation with other genes on the person's DNA.

**Comment by LimesKey** [comment]
After some more testing on the program, one of the negatives of the program is that it's incredibly resource-intensive. With a high-performance computer with an 8-core CPU and 16GB of Physical RAM and over 150GB of Virtual Memory on an NVMe SSD, it used up 140GB of combined Physical + Virtual RAM + 80% Core Utilization.

This was only for creating a database for a 3.2GB Sequenced DNA file (uncompressed), I'm not sure if we can provide the created database file for the user who downloads the program or if they have to create the database file themselves to be used with their Fasta file (DNA file).

**Comment by Verisimilitude11** [comment]
@LimesKey, I added both of the above features as an issue with https://github.com/Verisimilitude11/DNAnalyzer/issues/231 and https://github.com/Verisimilitude11/DNAnalyzer/issues/232.

**Comment by LimesKey** [comment]
@Verisimilitude11, sounds good, I first wanted to see everyone's ideas and thoughts on it first before I did more research on the performance part.

**Comment by LimesKey** [comment]
With the current development of more features like the GUI & the FAB File format, it'll be too difficult to incorporate this directly into the program and it might be easier to create our own in a way.

**Comment by LimesKey** [comment]
So far, we have made the decision to not re-write this in Rust or another programming language but to implement it directly with minor tweaks.

**Comment by LimesKey** [comment]
Closed due to high performance costs and a potential alternative: [Rust-Bio](https://github.com/rust-bio/rust-bio)
