### ISSUE TITLE
JUnit Test skeleton doesn't work

### ISSUE THREAD

**Issue by MartinGallauner** [Verisimilitude11/DNAnalyzer#237]
Gradle can't find any tests to execute.
```
Execution failed for task ':test'.
No tests found for given includes: [DNAnalyzer.MainTest.mainClassshouldExist](--tests filter)
```

**To Reproduce**
Run tests inside class MainTest with Gradle (using IntelliJ)

**Expected behavior**
The one initially created test is executed correctly

**Comment by Verisimilitude11** [comment]
@MartinGallauner what do you see when you run the following commands:
`.\gradlew build`
and
`java -jar build/libs/DNAnalyzer.jar assets/dna/random/dnalong.fa --amino=ser --min=10 --max=100`

**Comment by Verisimilitude11** [comment]
@MartinGallauner, did this issue get resolved?
