### ISSUE TITLE
setup.bat setup program for Windows 

### ISSUE THREAD

**Issue by LimesKey** [Verisimilitude11/DNAnalyzer#249]
To make the process of running the program as easy as possible, a batch script could be implemented for Windows users as a way to do 3 things in 1 click,

- Uncompress DNA Files
- Build Gradle
- CD into the executable program's directory, It would open up a terminal window with the current directory of the program, allowing users to skip the CD step.

It would implement the functionality of the following PowerShell script:
```
Expand-Archive -LiteralPath assets/dna.zip -DestinationPath assets && rm assets/dna.zip
```

**Comment by plopez26DPU** [comment]
I've done some shell scripts, I'd like to try this one too

**Comment by LimesKey** [comment]
This might conflict with #242 so keep an eye out for that.

**Comment by Verisimilitude11** [comment]
@plopez26DPU, how far are you on this issue as well?

**Comment by Verisimilitude11** [comment]
Hey @plopez26DPU, I'm going to unassign you from this issue for the time being as you're kinda busy with school, which I totally understand! Let me know once you're ready to resume contributing again!

**Comment by LimesKey** [comment]
#338 Better explains the feature request

**Comment by Verisimilitude11** [comment]
Sounds good 👍👍
