### ISSUE TITLE
Improve buildCodonMap

### ISSUE THREAD

**Issue by garyglatfelter** [Verisimilitude11/DNAnalyzer#261]
Sure @garyglatfelter. Here are a couple of places in which you could look into implementing parallel streams/multithreading:
- protein/ProteinFinder.java/getProtein and /addProtein
- ReadingFrames.java
- DNAAnalysis.java/protein sequence

Thanks again for your interest in working on this. This will be useful to us, and I'm excited to see what you will implement.

_Originally posted by @Verisimilitude11 in https://github.com/Verisimilitude11/DNAnalyzer/issues/103#issuecomment-1288239634_

**Comment by garyglatfelter** [comment]
I will try with buildCodonMap. That should be straightforward.

**Comment by Verisimilitude11** [comment]
Alright cool, I assigned it to you.

**Comment by Verisimilitude11** [comment]
@garyglatfelter, not to rush you, but how far are you on this issue? Feel free to take more time, just checking in.

**Comment by garyglatfelter** [comment]
Well, it's coming along. Just .....not quite as quickly as I thought (time constraints/busy week). Curious on a couple of things though:

1) There isn't really a class that sort of encapsulates (not sure if that's the right word) the data object of interest. Would you be opposed to having a class that sort of acts as the container for the DNA string of interest, its corresponding codon map, and maybe the different reading frames as well. I'm not sure what would be the most appropriate name, but maybe class  named 'DnaSequence'.

2) The codon map in buildCodonMap is only interested in the number of occurrences for each codon within the dna string? Is that correct?

3) Do you think there would be any utility/benefit in also generating and storing the codon sequence encoded by the dna string input. By that I mean, say the dna String of interest is "gggggaggtggcgaggaagatgac". Would it be helpful to generate the corresponding sequence GLYCINE, GLYCINE, GLYCINE, GLYCINE, GLUTAMIC_ACID, GLUTAMIC_ACID, ASPARTIC_ACID, ASPARTIC_ACID and store it, perhaps as an instance variable in class DnaSequence?

**Comment by Verisimilitude11** [comment]
Hi @garyglatfelter, no worries.

1. I'm open to that, but what would be a benefit of encapsulating the DNA string?
2. That's correct
3. Could you please elaborate a bit more on this in the Discord server? I didn't completely understand what you mean by generating the corresponding sequence.

Thank you so much for contributing to DNAnalyzer!
