### ISSUE TITLE
Add call to highCoverageRegions() to CmdArgs

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#270]
Call this method:
https://github.com/Verisimilitude11/DNAnalyzer/blob/7b6a0d5bd0950c95765da5dcaa9ce3ab3dc5b3b8/src/main/java/DNAnalyzer/protein/ProteinAnalysis.java#L26-L52

In:
CmdArgs after printing the nucleotide percentages.

**Comment by jaybob007** [comment]
I'd like to work on this, can you assign me to it?

**Comment by Verisimilitude11** [comment]
Sure @jaybob007. Please join our Discord server (https://discord.gg/5ShCNmyp) and star this repository to show your support.
