### ISSUE TITLE
Refactor ProteinFinder.addProtein(String,List<String>,int,List<String>)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#273]
I've selected [**ProteinFinder.addProtein(String,List<String>,int,List<String>)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/36f7bad03e75bcbcdca7a38852c48754bb27b149/src/main/java/DNAnalyzer/protein/ProteinFinder.java#L80-L98) for refactoring, which is a unit of **10** lines of code and **4** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Ravina-Deogadkar** [comment]
Can I work on this?

**Comment by Verisimilitude11** [comment]
Sure @Ravina-Deogadkar, I assigned it to you.

**Comment by Verisimilitude11** [comment]
@Ravina-Deogadkar how far are you on this issue?

**Comment by Ravina-Deogadkar** [comment]
I am done, I will send PR today

**Comment by Verisimilitude11** [comment]
> I am done, I will send PR today

Sounds good, thanks!

**Comment by Ravina-Deogadkar** [comment]
Added PR https://github.com/Verisimilitude11/DNAnalyzer/pull/294
