### ISSUE TITLE
Refactor DNAAnalysis.countBasePairs(String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#274]
I've selected [**DNAAnalysis.countBasePairs(String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/36f7bad03e75bcbcdca7a38852c48754bb27b149/src/main/java/DNAnalyzer/DNAAnalysis.java#L112-L136) for refactoring, which is a unit of **22** lines of code and **5** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by garyglatfelter** [comment]
@Verisimilitude11 I have fixed it per the above guidelines

**Comment by garyglatfelter** [comment]
Whoops. I moved the array around and I didn't catch that the null test failed :flushed:
