### ISSUE TITLE
Get User Input for the DNA File

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#29]
### Current
Currently, the user has to change the name of the DNA file by going through the code which is unnecessarily more complicated.

### Action item
Get input from the user for the DNA file to be processed. Perhaps we can use the Scanner class through Java Utilities.

### Alternatives
I tried using the scanner class but it says file not found for some reason.

### Additional context
This change would need to be implemented in the `GenomeSequencer.java` file.

**Comment by Kit-p** [comment]
Hi @Verisimilitude11, saw your post in the hacktoberfest Discord server, is it okay if I work on this issue?

It seems like `GenomeSequencer.java` does not exist anymore, I think currently the change would be in `CoreExecutor.java`?

**Comment by Verisimilitude11** [comment]
Of course! Do keep in mind that hacktoberfest officially starts on October 1st, so open your pull request after that date for it to be eligible for the challenge. You are correct, it should be in `CoreExecutor.java`, after the rename. I've assigned this issue the `hacktoberfest-accepted` label, which means that you should be all set to contribute. Please let me/the dev team know if you have any questions/feedback. Thanks again for your interest in contributing to the world of open source!

**Comment by Kit-p** [comment]
Thank you!
