### ISSUE TITLE
Invalid characters present in DNA sequence.

### ISSUE THREAD

**Issue by LimesKey** [Verisimilitude11/DNAnalyzer#293]
I'm getting ``java.lang.IllegalArgumentException: Invalid characters present in DNA sequence.`` with the standard example "GRch38dnapart.fa" file, I believe this is because it uses capital letters.

```
public record DNATools(String dna) {
    public void isValid() {
        if (!dna.matches("[atgc]+")) {
            throw new IllegalArgumentException("Invalid characters present in DNA sequence.");
```

Shouldn't this also include capital letters as valid too? Lowercase letters in FASTA files simply mark that section as repetitive and uppercase letters mark it as non-repetitive or original. This should allow for that.

**Comment by Verisimilitude11** [comment]
I'm going to look into this. When I first coded DNAnalyzer, I had a method that converted the entire DNA string to lowercase, so isValid() would have worked. Someone may have accidentally removed in a PR though so I'll have to add it back.

**Comment by Verisimilitude11** [comment]
@LimesKey do you still see this bug occurring?

**Comment by LimesKey** [comment]
Nope, the bug appears to be fixed.
