### ISSUE TITLE
(JAVA-E0029) Unsafe usage of `getResource`

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#301]
## Description
Usage of `getResource` may be unsafe if this class is extended.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-E0029/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-E0029/occurrences/)

**Comment by Ravina-Deogadkar** [comment]
Hi, Can I take a look into this issue?

**Comment by Verisimilitude11** [comment]
Sure @Ravina-Deogadkar.

**Comment by Verisimilitude11** [comment]
Hi @Ravina-Deogadkar, could you please remind me if you completed this issue already or not? Thanks for being a contributor to DNAnalyzer here and on dev.to!

**Comment by Ravina-Deogadkar** [comment]
Hi piyush, I have fixed it but my editor was causing some build issue so I'll try on different editor and then raise PR, I'll generate PR before weekend.

**Comment by Verisimilitude11** [comment]
Hi @Ravina-Deogadkar,

I'm glad to hear that you've made progress on this issue! Thank you for your dedication and hard work on DNAnalyzer.

If you run into any issues or have any questions while testing your fix on a different editor, please don't hesitate to reach out for help. I'm looking forward to seeing your PR and reviewing your code. Keep up the great work, and thanks again for your contributions to DNAnalyzer.

Best,
@Verisimilitude11

**Comment by Ravina-Deogadkar** [comment]
Added PR [#335](https://github.com/Verisimilitude11/DNAnalyzer/pull/335)
