### ISSUE TITLE
Proposal: Enhanced Modularization for better Extensibility

### ISSUE THREAD

**Issue by Kit-p** [Verisimilitude11/DNAnalyzer#303]
**Is your feature request related to a problem? Please describe.**
As the project grows in complexity, the main package will become cluttered with code for things like I/O handling, CLI/GUI interfaces, etc.. It will become difficult to onboard new contributors, and impossible for other projects to be extended from here.

**Describe the solution you'd like**
Code for different aspects should be separated into self-containing modules, be it a package in Java's term or even entirely different repositories (which is good for allowing different languages).
A brief idea about how the line can be drawn:

| Module   | Purpose                        |
| -------- | ------------------------------ |
| `core`   | Computation Logic              |
| `client` | CLI / GUI (Desktop, Web, etc.) |
| `util`   | Utilities (maybe I/O handlers) |

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Verisimilitude11** [comment]
Thanks for the issue @Kit-p! @Speedro, do you want to take a look at it?

**Comment by Speedro** [comment]
LGTM 🙂, maybe one thing - the ui related logic can be inside ui package. Client code is often related to the code that handles other app integration logic.

**Comment by iaacornus** [comment]
the utils can be further divided into `core` (main dependency of vital functions), `misc` (is not a requirement for vital functions), and other subpackages which assists the program. Then the `core` contains the modules which will constitute the main logic. Then `shared`, which is also like utils, but multiple packages/modules depend on it, this can also be broken down into `core` and `misc`. `data`/`resources` package will then contain the dataclass (not sure what is its equivalent in java) or any constants that the program uses, e.g. codons and profiles. Then finally a `main.java` in the `src` source which would merge/call all of it:

Example layout (disregard the filler names):

```
src/
├── data or resources/
│   └── dna/
│   │   ├── codons.java
│   │   └── profiles.java
├── client/
│   └── gui/
│   │   └── ...
├── core/
│   └── inferences.java
├── main.java
├── shared
│   └── pattern_matching.so
└── utils
    ├── core
    │   └── dna_complimentary.java
    └── misc
        └── stdout.java
```
