### ISSUE TITLE
(JAVA-W1058) JUnit5 test classes and methods should be package-private

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#305]
## Description
JUnit5 test classes and methods should be package-private.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1058/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1058/occurrences/)

**Comment by Ravina-Deogadkar** [comment]
Hi, can I take this issue?

**Comment by Verisimilitude11** [comment]
Sure @Ravina-Deogadkar, I assigned the issue to you.

**Comment by Ravina-Deogadkar** [comment]
Created pull request #319
