### ISSUE TITLE
Add user feedback tools to DNAnalyzer

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#332]
DNAnalyzer should include tools for gathering user feedback, such as rating systems or feedback forms, to help improve the software based on the needs and preferences of its users. This could include a system for users to rate the software or leave comments and suggestions. User feedback tools would allow us to better understand how users are using DNAnalyzer and what they would like to see added or improved in future updates.

**Comment by Ravina-Deogadkar** [comment]
Hi, I want to work on this

**Comment by JasmeetSingh30** [comment]
Hello, I have 5 years of experience with coding, worked on many full stack tools. I can contribute to this, please give me a chance.

**Comment by Verisimilitude11** [comment]
Hi @Ravina-Deogadkar and @JasmeetSingh30! I see that both of you are interested in working on this issue, that's not a problem! I think that @Ravina-Deogadkar can work on creating the rating system tool and @JasmeetSingh30 can create the feedback forms. Does that sound like a good plan? If so, I'll split this issue into 2 so that we can collaborate on it effectively. Thank you so much for your interest in contributing!

**Comment by Verisimilitude11** [comment]
@JasmeetSingh30 please remember to star our repository to show your support!

**Comment by Ravina-Deogadkar** [comment]
Sure, Thanks....

**Comment by Verisimilitude11** [comment]
@Ravina-Deogadkar and @JasmeetSingh30, how far are you on this issue?

**Comment by Ravina-Deogadkar** [comment]
I didn't got time but I'll start on weekend.

**Comment by Verisimilitude11** [comment]
Sounds good, thank you @Ravina-Deogadkar!

**Comment by Ravina-Deogadkar** [comment]
I added the Rating UI page (Not integrated with DB). Do you think this looks good? 
And also does the integration with DB need to be covered in this issue?

https://user-images.githubusercontent.com/49125074/212471074-b1fabca1-a177-4341-a5ed-ad3b03d092fc.mp4
