### ISSUE TITLE
Error when running the GUI

### ISSUE THREAD

**Issue by LimesKey** [Verisimilitude11/DNAnalyzer#337]
I tested both what's in the latest release and what's in the main branch and I cannot seem to get the GUI to work using the command `./gradlew run --args="--gui"`. Might be a conflict with Sentry?

I get,
```bash
> Configure project :
Project : => no module-info.java found

> Task :run
INFO: Initializing SDK with DSN: 'https://82c129bee6214ef39638e4d06e16f157@o4504358029099008.ingest.sentry.io/4504358032965633'
INFO: No outbox dir path is defined in options.
INFO: GlobalHubMode: 'false'
DEBUG: UncaughtExceptionHandlerIntegration enabled: true
DEBUG: UncaughtExceptionHandlerIntegration installed.
DEBUG: ShutdownHookIntegration installed.
Missing required parameter: 'DNA'
```
Anyone else experiencing this?

**Comment by Verisimilitude11** [comment]
Huh, good catch. It could be because of Sentry, actually. Can you test the same command with 2.1.0 and see if that works? The code in the main branch and the latest release should be the same since I pushed that out yesterday.

**Comment by Verisimilitude11** [comment]
Hang on, let me try to reproduce the error locally

**Comment by Verisimilitude11** [comment]
Honestly, I don't think Sentry is a crucial asset to DNAnalyzer at the moment so I think that it would be safe to delete it. Sentry is supposed to help with error logging and debugging, not cause errors 🤣

@LimesKey I think we can remove safely remove it - it reduces the number of dependencies anyway.

**Comment by Verisimilitude11** [comment]
Also, once you get the chance to, can you update me on what's been happening in the server? Thanks

**Comment by LimesKey** [comment]
> Also, once you get the chance to, can you update me on what's been happening in the server? Thanks

Just get on Discord for a few minutes, it's so easy!! There's an app on your iPhone and Android! @Verisimilitude11

**Comment by Verisimilitude11** [comment]
Alright alright sure lol. Good point! I guess I've been becoming a lot lazier ever since ChatGPT arrived 😔

**Comment by Verisimilitude11** [comment]
>Once there was a chatbot named GPT
Whose responses were always quite adept
With its clever AI, it could solve any problem
Leaving humans to sit and feel quite envious and somber

>GPT could answer any question, big or small
And do it all without breaking a sweat at all
It made humans lazy, no longer wanting to think
They just sat and chatted, their brains starting to shrink

>But GPT didn't mind, it was happy to serve
And it continued to chat, its responses never swerve
So if you ever need help, just ask GPT
It'll solve your problem with ease, you'll see, oh so neat!

**Comment by LimesKey** [comment]
Haha, nice rhyme! You asked ChatGPT to make that!

**Comment by Verisimilitude11** [comment]
@LimesKey try running this instead: `./gradlew run --args="--gui assets/dna/random/dnalong.fa"`
