### ISSUE TITLE
Find a company that will genotype/sequence your DNA for the lowest price in US

### ISSUE THREAD

**Issue by LimesKey** [Verisimilitude11/DNAnalyzer#341]
To get a good idea of the process and what the end user might experience. We would like to give the users a good idea of what to expect price-wise and how the whole process will work.

The website must be one of the cheapest ones available while providing a genotyped file to download your genome code. The company must have a easy way to ship the sample (saliva) to the company with ok shipping.

**Comment by LimesKey** [comment]
Shouldn't be too difficult, you just need some Google-Fu. Beginner contributors-friendly!

**Comment by alexeiMikhail** [comment]
I'd like to tackle this one, do I need to be assigned or anything?

**Comment by Verisimilitude11** [comment]
Sounds good, let me assign you! Feel free to ask for help or more information here or in the Discord server.

**Comment by LimesKey** [comment]
I know @alexeiMikhail your working on it but I had some time to spare and did the sequencing ones myself. You can do the genotyping companies instead if you'd like.

| Company | Quality | Price | Link 
| :---           |    :----:  | :----: | :----: |
| Sequencing|30x|$399USD|[Sequencing.com ](https://sequencing.com/products/purchase-kit)
|Nebula|30x|$175USD|[Nebula.org](https://nebula.org/ownership-of-your-genetic-data/)
|Dante Labs|30x|$200USD|[us.dantelabs.com](https://us.dantelabs.com/products/whole-genome-sequencing?variant=31588228759618)

All of these are from the US and all of them are Whole Genome Sequencing (WGS) and not genotyping. I believe that all also take saliva samples and ship the kits within a few weeks.

**Comment by alexeiMikhail** [comment]
I also found this one for sequencing:

[Full Genomes](https://www.fullgenomes.com/whole-genome-sequencing/) $1150 30x quality

I haven't had any luck so far finding genotyping.

**Comment by alexeiMikhail** [comment]
Sorry, but I think that's all I got. I vastly underestimated how difficult it would be for me to find.

**Comment by LimesKey** [comment]
> I also found this one for sequencing:
> 
> 
> 
> [Full Genomes](https://www.fullgenomes.com/whole-genome-sequencing/) $1150 30x quality
> 
> 
> 
> I haven't had any luck so far finding genotyping. 
> 
> 

23AndMe, one of the biggest DNA testing comapanies in DNA does genotyping for a few hundred dollars

**Comment by LimesKey** [comment]
> Sorry, but I think that's all I got. I vastly underestimated how difficult it would be for me to find. 

No worries, looks good, feel free to help in other open issues. I just searched reddit on r/genetics and asked ChatGTP of some companies.

I just went on that subreddit, searched "sequencing" and it gave me a list of people asking for DNA sequencing companies and then from that I found the best price companies.

**Comment by alexeiMikhail** [comment]
Smart. I didn't even think to check reddit. I found a few articles about direct to consumer sequencing and SNP, but a lot of the company websites were down.

**Comment by Verisimilitude11** [comment]
Thanks for helping us with this issue @alexeiMikhail! We would really appreciate it if you could star our repository to show your support! Thanks!!
