### ISSUE TITLE
(JAVA-C1002) Wrong argument order in test assertions

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#342]
## Description
Argument ordering conventions must be followed for assertions in their respectice libraries.

## Occurrences
There are 19 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-C1002/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-C1002/occurrences/)

**Comment by Rishav1707** [comment]
Do you want this to be removed

**Comment by Verisimilitude11** [comment]
No, this issue is still open. Do you want me to assign it to you?
