### ISSUE TITLE
(JAVA-W1064) Redundant boolean literal

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#344]
## Description
Boolean literals should not be used redundantly within expressions.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1064/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1064/occurrences/)

**Comment by Rishav1707** [comment]
After removing these Boolean literals what you want to add in place of Boolean literals
