### ISSUE TITLE
(JAVA-W1069) Unnecessary imports detected

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#345]
## Description
Unused imports should be removed from all source files.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1069/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1069/occurrences/)

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Verisimilitude11
