### ISSUE TITLE
Update Docs to Reflect Current Code

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#68]
Update README.md to reflect current features and add visuals to make it easier to understand/look good.

**Comment by iamHrithikRaj** [comment]
can you elaborate more on this issue?

**Comment by Verisimilitude11** [comment]
Done! Let me know if you need additional clarification.

**Comment by iamHrithikRaj** [comment]
aight got it, you can assign this to me. I'd like to work on it

**Comment by Verisimilitude11** [comment]
Sounds good!
