### ISSUE TITLE
Refactor Properties.formatNucleotideCount(String,int,String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#70]
I've selected [**Properties.formatNucleotideCount(String,int,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/Properties.java#L103-L105) for refactoring, which is a unit of **3** lines of code and **3** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by harikesh409** [comment]
Can you assign this to me

**Comment by harikesh409** [comment]
It's already having 3 parameters what kind of refactoring are you expecting?

**Comment by Verisimilitude11** [comment]
Apologies! I think that this issue was already fixed. Thanks for noticing. Feel free to work on another open issue!
