### ISSUE TITLE
Refactor ProteinFinder.getProtein(String,String,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#72]
I've selected [**ProteinFinder.getProtein(String,String,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList,ArrayList)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/ProteinFinder.java#L26-L84) for refactoring, which is a unit of **42** lines of code and **23** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by shubhwip** [comment]
Can you please assign this to me ?

**Comment by Verisimilitude11** [comment]
Sure!

**Comment by Verisimilitude11** [comment]
To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. After making changes, create a pull request. I usually accept PRs within 12 hours, just in case you do want to be one of the 40,000 that get a t-shirt for Hacktoberfest!
