### ISSUE TITLE
Refactor Properties.countNucleotides(String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#74]
I've selected [**Properties.countNucleotides(String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/Properties.java#L114-L128) for refactoring, which is a unit of **14** lines of code and **5** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Speedro** [comment]
Hi @Verisimilitude11 I would like to try to refactor this one. Is that possible?

**Comment by Verisimilitude11** [comment]
Sure. Make sure to create the PR after October 1st to ensure that it is eligible for Hacktoberfest.

**Comment by Verisimilitude11** [comment]
Thanks @Speedro for working on this issue! To support the mission of DNAnalyzer, I'd really appreciate it if you would give this repository a star! Thanks again for your contributions!
