### ISSUE TITLE
Refactor Properties.printProteinList(ArrayList,String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#76]
I've selected [**Properties.printProteinList(ArrayList,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/Properties.java#L35-L74) for refactoring, which is a unit of **33** lines of code and **20** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Speedro** [comment]
Hi @Verisimilitude11 I would take this one as well, as it might colied with some code changes from #74 (Property class) so we can avoid some merge conflicts with others...

**Comment by Verisimilitude11** [comment]
Sure, good idea. I assigned it to you.

**Comment by Verisimilitude11** [comment]
@Speedro how far are you on this issue?

**Comment by Speedro** [comment]
@Verisimilitude11 Haven't yet started, wanted to resolve #79 first. If I am blocking someone else feel free to reassign this. ☺️

**Comment by Verisimilitude11** [comment]
No worries, I was just checking in!
