### ISSUE TITLE
Refactor CoreExecutor.defaultCaller()

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#79]
I've selected [**CoreExecutor.defaultCaller()**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/CoreExecutor.java#L114-L159) for refactoring, which is a unit of **26** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Speedro** [comment]
Hi @Verisimilitude11 I would like to try to refactor this one. Is it possible?

**Comment by Verisimilitude11** [comment]
Sure, please feel free to ask me any questions that you may have!

**Comment by Verisimilitude11** [comment]
To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. After making changes, create a pull request. I usually accept PRs within 12 hours, just in case you do want to be one of the 40,000 that get a t-shirt for Hacktoberfest!

**Comment by codingmickey** [comment]
Can I work on this or the previous contributor is still going on?

**Comment by Speedro** [comment]
Hi @codingmickey I am still working on this.

**Comment by Verisimilitude11** [comment]
> Can I work on this or the previous contributor is still going on?

Feel free to work on one of our other open issues! To support the mission of DNAnalyzer, I'd really appreciate it if you would give this repository a star! Thanks again for your contributions!
