### ISSUE TITLE
Refactor Properties.printProteinList(ArrayList,String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#81]
I've selected [**Properties.printProteinList(ArrayList,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/5092890e50acec640441254ba5196a045f219f18/src/DNAnalyzer/Properties.java#L35-L74) for refactoring, which is a unit of **33** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by Speedro** [comment]
Possible duplicate for #76 ?

**Comment by Verisimilitude11** [comment]
I don't think so...Since they're dealing with the same file, maybe you can work on both of these.

**Comment by Kaushik-Iyer** [comment]
Can I try to work on this?

**Comment by Verisimilitude11** [comment]
Sure!

**Comment by Kaushik-Iyer** [comment]
Sorry, I'm not able to figure out a solution. You can assign this to someone else

**Comment by garyglatfelter** [comment]
Hi,

I might be able to help. I'm not sure what the _best_ way to do it is, but I can think of an _ok-ish_ way to do it. I'm thinking Properties should have a Map data field where the different keys (variations of amino acid name) has values set to the full name. Let me know if you'd like me to try that out.

**Comment by Verisimilitude11** [comment]
Sure, feel free. This seems like a good solution. I'll approve your PRs as they come in. Thanks for your help!

**Comment by Verisimilitude11** [comment]
Thanks @garyglatfelter for working on this issue! To support the mission of DNAnalyzer, I'd really appreciate it if you would give this repository a star! Thanks again for your contributions!

**Comment by Verisimilitude11** [comment]
@garyglatfelter how far are you on this issue?

**Comment by garyglatfelter** [comment]
Hi @Verisimilitude11, I've refactored but I'm unable to confirm it is without errors.
It could be that I am running it incorrectly, I receive errors on the main branch previous to any alterations I made.

I run
`"C:\Users\garyg\Documents\jdk-14.0.1\bin\java --enable-preview DNAnalyzer.Main --amino=histidine --min=3 --max=5 C:\Users\garyg\Documents\projects\DNAnalyzer\assets\dna\real\brca1line.fa"`

I get:
```
Proteins coded for Histidine:
----------------------------------------------------
1. CATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAATTTTTAA
2. CACCATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAATTTTTAA

GC-content (genome): 0.35871878

Nucleotide count:
A: 3790 (36.675053%)
T: 2837 (27.453068%)
G: 1903 (18.414942%)
C: 1804 (17.456938%)

java.lang.StringIndexOutOfBoundsException: begin 10333, end 10336, length 10334
Codons in reading frame 1 (3-5 occurrences):
----------------------------------------------------
CCG: 5
GCG: 5
TCG: 5
CGC: 3
```

**Comment by garyglatfelter** [comment]
Hmm.. so it looks like the error I'm getting is coming from printCodonCounts() in ReadingFrames.java.

I do see that AminoAcidMappings had some mapping already that complemented my approach.

I went with EnumMap instead of HashMap.(according to https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html:
"Implementation note: All basic operations execute in constant time. They are likely (though not guaranteed) to be faster than their [HashMap](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html) counterparts.")

I'm not entirely sure how to test it to make sure it is working correctly. What are some known correct inputs and known correct outputs?

**Comment by Verisimilitude11** [comment]
Hi @garyglatfelter sorry for the delay. Going with EnumMap sounds like a great idea!

I'm currently troubleshooting some issues on my system, so I won't be able to get back to you until tomorrow morning (12 hours). I'll give you some verified sample inputs for testing, but for now, ignore printCodonCounts and run it with methionine and assets/dna/random/dnalong.fa in reading frame 1. For min and max, just say 10-10000 for now until I tell you what the actual values should be. Hopefully that helps!

**Comment by Verisimilitude11** [comment]
> Hi @Verisimilitude11, I've refactored but I'm unable to confirm it is without errors. It could be that I am running it incorrectly, I receive errors on the main branch previous to any alterations I made.
> 
> I run `"C:\Users\garyg\Documents\jdk-14.0.1\bin\java --enable-preview DNAnalyzer.Main --amino=histidine --min=3 --max=5 C:\Users\garyg\Documents\projects\DNAnalyzer\assets\dna\real\brca1line.fa"`
> 
> I get:
> 
> ```
> Proteins coded for Histidine:
> ----------------------------------------------------
> 1. CATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAATTTTTAA
> 2. CACCATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAATTTTTAA
> 
> GC-content (genome): 0.35871878
> 
> Nucleotide count:
> A: 3790 (36.675053%)
> T: 2837 (27.453068%)
> G: 1903 (18.414942%)
> C: 1804 (17.456938%)
> 
> java.lang.StringIndexOutOfBoundsException: begin 10333, end 10336, length 10334
> Codons in reading frame 1 (3-5 occurrences):
> ----------------------------------------------------
> CCG: 5
> GCG: 5
> TCG: 5
> CGC: 3
> ```
> 
> any ideas what I'm doing wrong?

That's a really weird issue. Let me look into it and get back to you.

**Comment by garyglatfelter** [comment]
It looks like the printProteinList has been refactored already so somebody must have figure it out.

**Comment by Verisimilitude11** [comment]
Sounds good. Thanks for noticing this!
