### ISSUE TITLE
Code of Conduct file is missing !!

### ISSUE THREAD

**Issue by sumitbishti** [Verisimilitude11/DNAnalyzer#83]
I can add the file for you.

**Comment by Verisimilitude11** [comment]
Sounds great @sumitbishti!

**Comment by sumitbishti** [comment]
Could you please add Hacktoberfest label on to it?

**Comment by sumitbishti** [comment]
Actually you already have that file. Should I add Contributing-Guidelines file then ?

**Comment by Verisimilitude11** [comment]
Sure. that seems like a good idea. Feel free to update and add more documentation as you see fit. I'll add the `Hacktoberfest-accepted` label to all of the issues that you open.

**Comment by sumitbishti** [comment]
Very well then. Thank you for that.

**Comment by Verisimilitude11** [comment]
No problem. If you get time, create another issue for style guidelines as well.

**Comment by sumitbishti** [comment]
Sure, I will keep that in mind.
