### ISSUE TITLE
Possible Refactor for Utility classes

### ISSUE THREAD

**Issue by B4CKF1SH** [Verisimilitude11/DNAnalyzer#84]
Some utility methods in this project are not marked as static when they could be, requiring unnecessary instancing.

As this doesn't belong strictly into any of the other refactors, I opened a new issue.
I am willing to create a PR for this.

**Comment by Verisimilitude11** [comment]
Sure thing, feel free to get started on this. Please let me know if you have any questions. I added the `hacktoberfest-accepted` label to this issue.

**Comment by Verisimilitude11** [comment]
To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. After making changes, create a pull request. I usually accept PRs within 12 hours, just in case you do want to be one of the 40,000 that get a t-shirt for Hacktoberfest!
