### ISSUE TITLE
Check and Update Javadocs

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#90]
**Describe the solution you'd like**
Verify that Javadocs match the class/method's purpose (@param and @return, description, etc. are accurate). If there are inconsistencies present, please update them. Additionally, please add more comments throughout the code as well as more details to the Javadocs.

**Additional context**
<img width="237" alt="image" src="https://user-images.githubusercontent.com/96280466/193379930-58a7b33c-7059-407d-b590-fbdeb7004230.png">

**Comment by iamHrithikRaj** [comment]
hey, I would like to work on this

**Comment by Verisimilitude11** [comment]
Sounds good, this will require a lot of cross-checking so please let me know if you face any issues or have any questions/concerns. Thanks for helping us out, we really appreciate it!

**Comment by Verisimilitude11** [comment]
To get started, navigate to our GitHub repository: https://github.com/Verisimilitude11/DNAnalyzer and fork it. Take some time to read the documentation and to acquaint yourself with the code. After making changes, create a pull request. I usually accept PRs within 12 hours, just in case you do want to be one of the 40,000 that get a t-shirt for Hacktoberfest!
