### ISSUE TITLE
[Documentation] Code Conventions and Style Guidelines

### ISSUE THREAD

**Issue by sumitbishti** [Verisimilitude11/DNAnalyzer#95]
A markdown file stating all the necessary Code conventions and style guidelines for DNAnalyzer Project.
And a minor typo at Contributing_Guidelines.md file!

**Comment by Verisimilitude11** [comment]
@sumitbishti how far are you on this issue?

**Comment by sumitbishti** [comment]
@Verisimilitude11 I'm half way through it. Since your codebase is on java do you want java specific guidelines or just general ones?
